apiVersion: v1
kind: Namespace
metadata:
  name: fulfillment
---
apiVersion: v1
data:
  BFF_URL: http://customer-bff:8080
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  OIDC_ISSUER: https://identity.example.com/realms/shop
  OIDC_JWKS: https://identity.example.com/realms/shop/protocol/openid-connect/certs
  ORDER_URL: http://order-service:8080
  PROVIDER_URL: http://provider-simulator:8080
  QUERY_URL: http://order-query-service:8080
  REDIS_HOST: redis
kind: ConfigMap
metadata:
  name: fulfillment-config
  namespace: fulfillment
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: fulfillment
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    app: api-gateway
---
apiVersion: v1
kind: Service
metadata:
  name: customer-bff
  namespace: fulfillment
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    app: customer-bff
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: fulfillment
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    app: inventory-service
---
apiVersion: v1
kind: Service
metadata:
  name: order-query-service
  namespace: fulfillment
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    app: order-query-service
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: fulfillment
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    app: order-service
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: fulfillment
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    app: payment-service
---
apiVersion: v1
kind: Service
metadata:
  name: provider-simulator
  namespace: fulfillment
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    app: provider-simulator
---
apiVersion: v1
kind: Service
metadata:
  name: shipping-service
  namespace: fulfillment
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    app: shipping-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: fulfillment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      automountServiceAccountToken: false
      containers:
      - envFrom:
        - configMapRef:
            name: fulfillment-config
        image: fulfillment/api-gateway:local
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: http
          periodSeconds: 10
        name: application
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: http
          periodSeconds: 5
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        startupProbe:
          failureThreshold: 60
          httpGet:
            path: /actuator/health/readiness
            port: http
          periodSeconds: 5
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir:
          sizeLimit: 128Mi
        name: tmp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-bff
  namespace: fulfillment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer-bff
  template:
    metadata:
      labels:
        app: customer-bff
    spec:
      automountServiceAccountToken: false
      containers:
      - envFrom:
        - configMapRef:
            name: fulfillment-config
        image: fulfillment/customer-bff:local
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: http
          periodSeconds: 10
        name: application
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: http
          periodSeconds: 5
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        startupProbe:
          failureThreshold: 60
          httpGet:
            path: /actuator/health/readiness
            port: http
          periodSeconds: 5
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir:
          sizeLimit: 128Mi
        name: tmp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: fulfillment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      automountServiceAccountToken: false
      containers:
      - env:
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              key: url
              name: inventory-service-database
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: inventory-service-database
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: inventory-service-database
        envFrom:
        - configMapRef:
            name: fulfillment-config
        image: fulfillment/inventory-service:local
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: http
          periodSeconds: 10
        name: application
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: http
          periodSeconds: 5
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        startupProbe:
          failureThreshold: 60
          httpGet:
            path: /actuator/health/readiness
            port: http
          periodSeconds: 5
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir:
          sizeLimit: 128Mi
        name: tmp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-query-service
  namespace: fulfillment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-query-service
  template:
    metadata:
      labels:
        app: order-query-service
    spec:
      automountServiceAccountToken: false
      containers:
      - env:
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              key: url
              name: order-query-service-database
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: order-query-service-database
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: order-query-service-database
        envFrom:
        - configMapRef:
            name: fulfillment-config
        image: fulfillment/order-query-service:local
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: http
          periodSeconds: 10
        name: application
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: http
          periodSeconds: 5
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        startupProbe:
          failureThreshold: 60
          httpGet:
            path: /actuator/health/readiness
            port: http
          periodSeconds: 5
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir:
          sizeLimit: 128Mi
        name: tmp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: fulfillment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      automountServiceAccountToken: false
      containers:
      - env:
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              key: url
              name: order-service-database
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: order-service-database
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: order-service-database
        envFrom:
        - configMapRef:
            name: fulfillment-config
        image: fulfillment/order-service:local
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: http
          periodSeconds: 10
        name: application
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: http
          periodSeconds: 5
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        startupProbe:
          failureThreshold: 60
          httpGet:
            path: /actuator/health/readiness
            port: http
          periodSeconds: 5
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir:
          sizeLimit: 128Mi
        name: tmp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: fulfillment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      automountServiceAccountToken: false
      containers:
      - env:
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              key: url
              name: payment-service-database
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: payment-service-database
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: payment-service-database
        - name: PROVIDER_KEY
          valueFrom:
            secretKeyRef:
              key: key
              name: simulator-credential
        envFrom:
        - configMapRef:
            name: fulfillment-config
        image: fulfillment/payment-service:local
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: http
          periodSeconds: 10
        name: application
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: http
          periodSeconds: 5
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        startupProbe:
          failureThreshold: 60
          httpGet:
            path: /actuator/health/readiness
            port: http
          periodSeconds: 5
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir:
          sizeLimit: 128Mi
        name: tmp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider-simulator
  namespace: fulfillment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: provider-simulator
  template:
    metadata:
      labels:
        app: provider-simulator
    spec:
      automountServiceAccountToken: false
      containers:
      - env:
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              key: url
              name: provider-simulator-database
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: provider-simulator-database
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: provider-simulator-database
        - name: PROVIDER_KEY
          valueFrom:
            secretKeyRef:
              key: key
              name: simulator-credential
        envFrom:
        - configMapRef:
            name: fulfillment-config
        image: fulfillment/provider-simulator:local
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: http
          periodSeconds: 10
        name: application
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: http
          periodSeconds: 5
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        startupProbe:
          failureThreshold: 60
          httpGet:
            path: /actuator/health/readiness
            port: http
          periodSeconds: 5
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir:
          sizeLimit: 128Mi
        name: tmp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service
  namespace: fulfillment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shipping-service
  template:
    metadata:
      labels:
        app: shipping-service
    spec:
      automountServiceAccountToken: false
      containers:
      - env:
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              key: url
              name: shipping-service-database
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: shipping-service-database
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: shipping-service-database
        - name: PROVIDER_KEY
          valueFrom:
            secretKeyRef:
              key: key
              name: simulator-credential
        envFrom:
        - configMapRef:
            name: fulfillment-config
        image: fulfillment/shipping-service:local
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: http
          periodSeconds: 10
        name: application
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: http
          periodSeconds: 5
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        startupProbe:
          failureThreshold: 60
          httpGet:
            path: /actuator/health/readiness
            port: http
          periodSeconds: 5
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir:
          sizeLimit: 128Mi
        name: tmp
